const RuleOffsets = NTuple{2, NTuple{2, Int}}

# Observable names supported by the stats pipeline. Every key written to the
# JLD2 output is generated by `OBSERVABLES` × {base, chi_, bind_, t_auto_,
# _err, chi__err, bind__err, t_auto__err}. Note: `t_auto` is the exponential
# autocorrelation time of `|x|` in equilibrium, extracted from a fit to its
# connected autocorrelation function — NOT to be confused with `t_rel`, the
# first-passage / relaxation time produced by `--mode=trel`.
const OBSERVABLES = ("m", "D")

"""
    get_rule(rule_name)

Return `(R_or, R_and)` as static `NTuple{2, NTuple{2, Int}}` pairs of (di, dj)
offsets.

For squeezing rules (`R`, `F`, `M`) the two tuples are the OR-neighbor set
and the AND-neighbor set; `update_site!` picks one at each update via the
`use_or_probability` coin flip.

`R3` has the same neighbor offsets as `R` but `mc_sweep!` dispatches to
`update_site_r3!` which additionally includes the site itself in both the
OR (east OR west OR self) and the AND (north AND south AND self). The
offsets alone don't distinguish R from R3 — the rule string does.

For Toom's NEC rule (`"Toom"`), there is no OR/AND distinction — the site
updates to the majority of itself and its north and east neighbors
(canonical Toom NEC). We reuse `R_or = R_and = ((-1,0), (0,1))` as the
neighbor offsets and `mc_sweep!` dispatches to `update_site_toom!`
instead of `update_site!`.

For the `"Ising"` rule, the site follows zero-T Glauber dynamics on the 2D
NN Ising model — it needs 4 neighbors, which don't fit the `RuleOffsets`
type (pair of pairs). `update_site_ising!` hardcodes the four NN offsets
internally, so the offsets returned here for Ising are dummies kept only
for API stability.

- "R":     R_or = ((0, 1), (0,-1)),  R_and = ((1, 0), (-1, 0))
- "R3":    same offsets as R; self-included in OR/AND
- "F":     R_or = ((1, 1), (0,-1)),  R_and = ((1, 0), (-1,-1))
- "M":     R_or = ((1, 0), (0,-1)),  R_and = ((1, 0), (0, 1))
- "Toom":  R_or = R_and = ((-1, 0), (0, 1))   # N, E (canonical NEC)
- "Ising": dummies; 4 NN offsets inlined in `update_site_ising!`

All rules use offsets with `|di|, |dj| ≤ 1`; the update functions rely on
this to use a cheap wrap-around instead of `mod1`.
"""
function get_rule(rule_name::AbstractString)::Tuple{RuleOffsets, RuleOffsets}
    if rule_name == "R" || rule_name == "R3"
        return ((0, 1), (0, -1)), ((1, 0), (-1, 0))
    elseif rule_name == "F"
        return ((1, 1), (0, -1)), ((1, 0), (-1, -1))
    elseif rule_name == "M"
        return ((1, 0), (0, -1)), ((1, 0), (0, 1))
    elseif rule_name == "Toom"
        return ((-1, 0), (0, 1)), ((-1, 0), (0, 1))
    elseif rule_name == "Ising"
        # Dummies — the real 4-NN offsets are inlined in update_site_ising!.
        return ((1, 0), (-1, 0)), ((0, 1), (0, -1))
    else
        error("Unknown rule: $rule_name. Supported: R, R3, F, M, Toom, Ising")
    end
end

# Cheap periodic wrap for offsets in {-1, 0, 1}. Cheaper than mod1 because it
# avoids integer division.
@inline _wrap(i::Int, L::Int) = i < 1 ? i + L : (i > L ? i - L : i)

"""
    update_site!(state, i, j, L, R_or, R_and, p, η; use_or_probability=0.5)

One asynchronous site update at `(i, j)`:

- with probability `p`, replace by a random bit drawn from Bernoulli((1+η)/2);
- else, with probability `use_or_probability`, OR the two R_or neighbors;
- else, AND the two R_and neighbors.

Writes the new value in place and returns it. Allocation-free on the hot path.
"""
@inline function update_site!(state::AbstractMatrix{Bool}, i::Int, j::Int, L::Int,
                              R_or::RuleOffsets, R_and::RuleOffsets,
                              p::Float64, η::Float64;
                              use_or_probability::Float64=0.5)
    if rand() < p
        result = rand() < (1 + η) / 2
    elseif rand() < use_or_probability
        @inbounds begin
            a = R_or[1]; b = R_or[2]
            n1 = state[_wrap(i + a[1], L), _wrap(j + a[2], L)]
            n2 = state[_wrap(i + b[1], L), _wrap(j + b[2], L)]
        end
        result = n1 | n2
    else
        @inbounds begin
            a = R_and[1]; b = R_and[2]
            n1 = state[_wrap(i + a[1], L), _wrap(j + a[2], L)]
            n2 = state[_wrap(i + b[1], L), _wrap(j + b[2], L)]
        end
        result = n1 & n2
    end
    @inbounds state[i, j] = result
    return result
end

"""
    update_site_r3!(state, i, j, L, R_or, R_and, p, η; use_or_probability=0.5)

Variant of the R-rule update where the site itself is included in both the
OR and the AND:

- with probability `p`, replace by a random bit drawn from Bernoulli((1+η)/2);
- else, with probability `use_or_probability`:
      s(i, j) ← s(i, j+1) OR s(i, j-1) OR s(i, j)
- else:
      s(i, j) ← s(i+1, j) AND s(i-1, j) AND s(i, j)

Uses the same neighbor offsets as `R` (via `get_rule("R3") == get_rule("R")`).
Writes in place; allocation-free.
"""
@inline function update_site_r3!(state::AbstractMatrix{Bool}, i::Int, j::Int, L::Int,
                                 R_or::RuleOffsets, R_and::RuleOffsets,
                                 p::Float64, η::Float64;
                                 use_or_probability::Float64=0.5)
    if rand() < p
        result = rand() < (1 + η) / 2
    elseif rand() < use_or_probability
        @inbounds begin
            a = R_or[1]; b = R_or[2]
            n1 = state[_wrap(i + a[1], L), _wrap(j + a[2], L)]
            n2 = state[_wrap(i + b[1], L), _wrap(j + b[2], L)]
            s  = state[i, j]
        end
        result = n1 | n2 | s
    else
        @inbounds begin
            a = R_and[1]; b = R_and[2]
            n1 = state[_wrap(i + a[1], L), _wrap(j + a[2], L)]
            n2 = state[_wrap(i + b[1], L), _wrap(j + b[2], L)]
            s  = state[i, j]
        end
        result = n1 & n2 & s
    end
    @inbounds state[i, j] = result
    return result
end

"""
    update_site_toom!(state, i, j, L, R_nn, p, η)

One asynchronous site update under Toom's NEC rule:
`s(r) ← maj(s(r), s(r + R_nn[1]), s(r + R_nn[2]))`, with probability `p` the
site is reset to a random bit drawn from Bernoulli((1+η)/2) instead.

`R_nn` holds the two neighbor offsets (defaults to `((1,1), (1,-1))` — NE, SE
— via `get_rule("Toom")`). Writes the new value in place and returns it.
Allocation-free on the hot path.
"""
@inline function update_site_toom!(state::AbstractMatrix{Bool}, i::Int, j::Int, L::Int,
                                   R_nn::RuleOffsets, p::Float64, η::Float64)
    if rand() < p
        result = rand() < (1 + η) / 2
    else
        @inbounds begin
            a = R_nn[1]; b = R_nn[2]
            n1 = state[_wrap(i + a[1], L), _wrap(j + a[2], L)]
            n2 = state[_wrap(i + b[1], L), _wrap(j + b[2], L)]
        end
        # 3-site majority: at least two of (self, n1, n2) must be true.
        result = (Int(state[i, j]) + Int(n1) + Int(n2)) >= 2
    end
    @inbounds state[i, j] = result
    return result
end

"""
    update_site_ising!(state, i, j, L, p, η)

One asynchronous site update under zero-temperature Glauber dynamics on the
2D NN Ising model: `σᵢ = 2 sᵢ − 1`, energy `E = −Σ_⟨ij⟩ σᵢσⱼ`. Let `k` be the
number of NN aligned with the site's current value. Flipping the site changes
the energy by `ΔE ∝ k − 2`, so:

- `k < 2`  ⇒ `ΔE < 0` ⇒ flip (majority disagree).
- `k == 2` ⇒ `ΔE = 0` ⇒ flip with probability 1/2.
- `k > 2`  ⇒ `ΔE > 0` ⇒ keep.

With probability `p` the site is instead reset to a random bit drawn from
Bernoulli((1+η)/2) (same noise model as the squeezing rules). The 4 NN
offsets are inlined; allocation-free on the hot path.
"""
@inline function update_site_ising!(state::AbstractMatrix{Bool}, i::Int, j::Int, L::Int,
                                    p::Float64, η::Float64)
    if rand() < p
        result = rand() < (1 + η) / 2
    else
        @inbounds begin
            s  = state[i, j]
            n1 = state[_wrap(i + 1, L), j]
            n2 = state[_wrap(i - 1, L), j]
            n3 = state[i, _wrap(j + 1, L)]
            n4 = state[i, _wrap(j - 1, L)]
        end
        k = Int(n1 == s) + Int(n2 == s) + Int(n3 == s) + Int(n4 == s)
        result = k < 2  ? !s :
                 k == 2 ? (rand() < 0.5 ? !s : s) :
                          s
    end
    @inbounds state[i, j] = result
    return result
end

"""
    _generate_ps(pmin, pmax, n_ps, pc, log_spacing) -> Vector{Float64}

Construct the `n_ps` sweep-point values. Default (linear) spacing mirrors the
original `range(pmin, pmax, length=n_ps)` behaviour. With `log_spacing=true`,
the points are log-uniform in `|p − pc|`, concentrating samples near pc. The
sign side of pc is auto-detected: if both `pmin` and `pmax` lie above pc we
return `pc + exp(range(log(pmin−pc), log(pmax−pc), …))`; if both lie below
pc we return `pc − exp(range(log(pc−pmin), log(pc−pmax), …))` (i.e. log-
uniform in `pc − p`). The scheme errors if the interval straddles pc, since
`|p − pc|` has a cusp at pc and no single-branch log-spacing makes sense.
"""
function _generate_ps(pmin::Float64, pmax::Float64, n_ps::Int,
                      pc::Float64, log_spacing::Bool)
    if !log_spacing
        return collect(range(pmin, pmax, length=n_ps))
    end
    if pmin > pc && pmax > pc
        return pc .+ exp.(range(log(pmin - pc), log(pmax - pc), length=n_ps))
    elseif pmin < pc && pmax < pc
        # endpoints are given in ascending p-order; translate to the |pc-p|
        # coordinate which reverses direction.
        return pc .- exp.(range(log(pc - pmax), log(pc - pmin), length=n_ps)) |>
               reverse
    else
        error("log_spacing=true: [pmin, pmax] must lie on one side of pc; " *
              "got pmin=$pmin, pmax=$pmax, pc=$pc")
    end
end

"""
    init_state(L, η, init_cond)

Initialize an L×L Bool state.

- "rand":          uniform random bits.
- "balanced_rand": random bits with exact magnetization (1+η)/2.
- "clean":         all 1 if η ≤ 0, all 0 if η > 0 (aligned *against* the bias).
- "aligned":       all 1 if η ≥ 0, all 0 if η < 0 (aligned *with* the bias).
                   For η = 0 this is indistinguishable from `"clean"`.
"""
function init_state(L::Int, η::Real, init_cond::AbstractString="rand")
    if init_cond == "rand"
        return rand(Bool, L, L)
    elseif init_cond == "balanced_rand"
        squashed = zeros(Bool, L * L)
        num_ones = round(Int, L * L * (1 + η) / 2)
        squashed[1:num_ones] .= true
        shuffle!(squashed)
        return reshape(squashed, L, L)
    elseif init_cond == "clean"
        return η > 0 ? zeros(Bool, L, L) : ones(Bool, L, L)
    elseif init_cond == "aligned"
        return η < 0 ? zeros(Bool, L, L) : ones(Bool, L, L)
    else
        error("Invalid init_cond: $init_cond. Supported: rand, balanced_rand, clean, aligned")
    end
end


"""
    init_state_with_domain(L, η, domain_size) -> Matrix{Bool}

Bias-aligned `clean` background with a centered circular minority domain of
radius `R = round(Int, domain_size * L)` (matches `init_cond="circ"` in
MemoryNCA/Ethan/helper_functions.jl). For `η ≤ 0` the background is all 1s
and the disk is flipped to 0s; for `η > 0` it's the opposite.
"""
function init_state_with_domain(L::Int, η::Real, domain_size::Real)
    state = init_state(L, η, "clean")
    R = round(Int, domain_size * L)
    cx = div(L, 2) + 1
    cy = div(L, 2) + 1
    R2 = R * R
    @inbounds for j in 1:L, i in 1:L
        if (i - cx)^2 + (j - cy)^2 < R2
            state[i, j] = !state[i, j]
        end
    end
    return state
end

# ---- per-configuration observables ----
#
# Each `{name}_value(state)` returns a Float64 per-site signed observable
# (roughly in [-1, 1], though D is in [-2, 2]). Adding a new observable here
# plus adding its short name to `OBSERVABLES` above is enough to propagate it
# through `compute_moments`, `monte_carlo!`, and `run_stats`.

"""
    magnetization_value(state) -> Float64

Per-configuration magnetization `m = (1/N) Σᵢ σᵢ` with `σᵢ = 2 sᵢ − 1 ∈ ±1`.
Value is in [-1, 1].
"""
@inline function magnetization_value(state::AbstractMatrix{Bool})
    L = size(state, 1)
    N = L * L
    return (2 * count(state) - N) / N
end

"""
    anisotropy_value(state) -> Float64

Per-configuration anisotropy `D = (1/N) Σᵢ (σᵢ σ_{i+x̂} − σᵢ σ_{i+ŷ})` with
`σᵢ = 2 sᵢ − 1 ∈ ±1`, measuring the x-vs-y imbalance of nearest-neighbor spin
correlations. Value is in [-2, 2]; vanishes for fully-aligned states and for
x/y-symmetric ensembles.
"""
@inline function anisotropy_value(state::AbstractMatrix{Bool})
    L = size(state, 1)
    d = 0
    @inbounds for j in 1:L, i in 1:L
        s  = 2 * state[i, j] - 1
        sx = 2 * state[_wrap(i + 1, L), j] - 1
        sy = 2 * state[i, _wrap(j + 1, L)] - 1
        d += s * sx - s * sy
    end
    return d / (L * L)
end

# Dispatch table: observable short name → per-configuration extractor.
const OBSERVABLE_VALUES = Dict{String, Function}(
    "m" => magnetization_value,
    "D" => anisotropy_value,
)

"""
    autocorr_window(x, d)

Autocorrelation of `x` out to lag `d` via a sliding window.
Returns a length-(d+1) vector, normalized so C[1] = 1.
"""
function autocorr_window(x::Vector{<:Real}, d::Int)
    n  = length(x)
    μ  = mean(x)
    σ² = mean(abs2, x .- μ)
    if σ² == 0
        return ones(Float64, d + 1)
    end
    C = zeros(Float64, d + 1)
    for k in 0:d
        C[k + 1] = sum((x[1:n-k] .- μ) .* (x[1+k:n] .- μ)) / (n - k) / σ²
    end
    return C
end

"""
    t_auto_from_corr(C; cmin=0.2, cmax=0.8)

Extract the exponential decay time of an autocorrelation function by
least-squares fitting log(C) over the window cmin ≤ C ≤ cmax, only using
lags before the first zero crossing. This is the autocorrelation time
`t_auto`, not to be confused with the first-passage / relaxation time
`t_rel` produced by `--mode=trel`.
"""
function t_auto_from_corr(C::Vector{Float64}; cmin::Float64=0.2, cmax::Float64=0.8)
    zero_cross = findfirst(i -> C[i] < 0, 2:length(C))
    zero_cross = zero_cross === nothing ? length(C) : zero_cross
    C_fit = C[1:zero_cross]
    idx = findall(i -> (C_fit[i] <= cmax) && (C_fit[i] >= cmin), 1:length(C_fit))
    if length(idx) ≤ 1
        return NaN
    end
    lags  = Float64.(idx .- 1)
    ys    = log.(C_fit[idx])
    Δ     = lags .- mean(lags)
    slope = dot(Δ, ys .- mean(ys)) / dot(Δ, Δ)
    return -1 / slope
end

"""
    block_jackknife_stats(obs_hist, N; n_blocks=32)

Block-jackknife error estimator for `⟨|x|⟩`, `χ = N·Var(|x|)`, and the Binder
cumulant `(3 − ⟨x⁴⟩/⟨x²⟩²)/2`, applied to a time series `obs_hist` of
per-site signed observable values (e.g. magnetization or D). `N` supplies the
extensive factor for `χ`.

Splits the series into `n_blocks` contiguous blocks to absorb autocorrelation,
then builds leave-one-block-out resamples. Returns `(mean_err, chi_err,
bind_err)`. Each error is `√((n−1)/n · Σᵢ(xᵢ − x̄)²)` over the `n_blocks`
jackknife replicates. Returns `NaN`s if the series is too short.
"""
function block_jackknife_stats(obs_hist::AbstractVector{<:Real}, N::Int;
                               n_blocks::Int=32)
    n = length(obs_hist)
    if n_blocks < 2 || n < 2 * n_blocks
        return NaN, NaN, NaN
    end
    b = div(n, n_blocks)
    S1 = zeros(Float64, n_blocks)
    S2 = zeros(Float64, n_blocks)
    S4 = zeros(Float64, n_blocks)
    @inbounds for i in 1:n_blocks
        lo = (i - 1) * b + 1
        hi = i * b
        s1 = 0.0; s2 = 0.0; s4 = 0.0
        for k in lo:hi
            x  = obs_hist[k]
            x2 = x * x
            s1 += abs(x)
            s2 += x2
            s4 += x2 * x2
        end
        S1[i] = s1; S2[i] = s2; S4[i] = s4
    end
    T1 = sum(S1); T2 = sum(S2); T4 = sum(S4)
    nb = (n_blocks - 1) * b
    m_jk    = Vector{Float64}(undef, n_blocks)
    chi_jk  = Vector{Float64}(undef, n_blocks)
    bind_jk = Vector{Float64}(undef, n_blocks)
    @inbounds for i in 1:n_blocks
        e1 = (T1 - S1[i]) / nb
        e2 = (T2 - S2[i]) / nb
        e4 = (T4 - S4[i]) / nb
        m_jk[i]    = e1
        chi_jk[i]  = N * (e2 - e1 * e1)
        bind_jk[i] = e2 == 0 ? NaN : (3 - e4 / (e2 * e2)) / 2
    end
    fac = (n_blocks - 1) / n_blocks
    m_err    = sqrt(fac * sum((m_jk   .- mean(m_jk)).^2))
    chi_err  = sqrt(fac * sum((chi_jk .- mean(chi_jk)).^2))
    bind_valid = filter(!isnan, bind_jk)
    bind_err = length(bind_valid) < 2 ? NaN :
               sqrt(fac * sum((bind_valid .- mean(bind_valid)).^2))
    return m_err, chi_err, bind_err
end

"""
    t_auto_jackknife_err(obs_abs, d; n_blocks=8)

Leave-one-block-out jackknife error for the magnetization autocorrelation
time `t_auto` extracted via `autocorr_window` + `t_auto_from_corr`. The series
`obs_abs` (typically `abs.(m_hist)` or `abs.(D_hist)`) is split into
`n_blocks` blocks, and `t_auto` is refit on each leave-one-out subset.
Returns the jackknife error in units of data-taking samples (callers
multiply by `data_taking_ratio` for MC-sweep units), or `NaN` if fewer
than two resamples converge.
"""
function t_auto_jackknife_err(obs_abs::AbstractVector{<:Real}, d::Int;
                              n_blocks::Int=8,
                              cmin::Float64=0.2, cmax::Float64=0.8)
    n = length(obs_abs)
    if n_blocks < 2
        return NaN
    end
    b = div(n, n_blocks)
    if b <= d + 1
        return NaN
    end
    keep = Vector{Float64}(undef, (n_blocks - 1) * b)
    τs = Float64[]
    for i in 1:n_blocks
        lo = (i - 1) * b + 1
        hi = i * b
        idx = 1
        @inbounds for k in 1:n
            if k < lo || k > hi
                keep[idx] = obs_abs[k]
                idx += 1
                idx > length(keep) && break
            end
        end
        C = autocorr_window(keep, d)
        τ = t_auto_from_corr(C; cmin=cmin, cmax=cmax)
        if !isnan(τ) && isfinite(τ)
            push!(τs, τ)
        end
    end
    if length(τs) < 2
        return NaN
    end
    fac = (n_blocks - 1) / n_blocks
    return sqrt(fac * sum((τs .- mean(τs)).^2))
end

"""
    compute_moments(hist, N; data_taking_ratio=20, cmin=0.2, cmax=0.8)

From a time series `hist` of per-site signed observable values (as produced by
e.g. `magnetization_value` or `anisotropy_value`), compute the standard finite-
size-scaling observables and 1σ statistical errors:

- `mean`       = ⟨|x|⟩
- `chi`        = N · Var(|x|)
- `bind`       = (3 − ⟨x⁴⟩/⟨x²⟩²) / 2
- `t_auto`     = magnetization autocorrelation time of `|x|` (the
  exponential decay time of the connected autocorrelation function),
  in MC sweeps. Distinct from `t_rel`, the first-passage / relaxation
  time produced by `--mode=trel`.
- `mean_err`, `chi_err`, `bind_err` — block-jackknife errors (32 blocks)
- `t_auto_err` — leave-one-out-block jackknife error on `t_auto`
  (8 blocks), converted to MC sweeps

Returns a `NamedTuple` with these eight fields. Fields that cannot be computed
(too few samples, zero variance) are returned as `NaN`.
"""
function compute_moments(hist::AbstractVector{<:Real}, N::Int;
                         data_taking_ratio::Int=20,
                         cmin::Float64=0.2, cmax::Float64=0.8)
    abs_hist = abs.(hist)
    mean_val = mean(abs_hist)
    chi      = N * var(abs_hist)
    m2       = mean(hist .^ 2)
    m4       = mean(hist .^ 4)
    bind     = m2 == 0 ? NaN : (3 - m4 / m2^2) / 2

    d = min(length(abs_hist) - 1, 4 * data_taking_ratio)
    t_auto     = NaN
    t_auto_err = NaN
    if d > 1
        C         = autocorr_window(abs_hist, d)
        τ_samples = t_auto_from_corr(C; cmin=cmin, cmax=cmax)
        t_auto    = τ_samples * data_taking_ratio
        τ_err     = t_auto_jackknife_err(abs_hist, d; cmin=cmin, cmax=cmax)
        t_auto_err = τ_err * data_taking_ratio
    end

    mean_err, chi_err, bind_err = block_jackknife_stats(hist, N)

    return (mean=mean_val, chi=chi, bind=bind, t_auto=t_auto,
            mean_err=mean_err, chi_err=chi_err, bind_err=bind_err,
            t_auto_err=t_auto_err)
end

@inline function hamming(a::AbstractMatrix{Bool}, b::AbstractMatrix{Bool})
    s = 0
    @inbounds @simd for k in eachindex(a)
        s += a[k] ⊻ b[k]
    end
    return s
end

"""
    accumulate_spatial!(corr_x, corr_y, state)

Accumulate spatial correlators
    Cₓ(r) += ⟨(1-2s_{i,j})(1-2s_{i+r,j})⟩,
    C_y(r) += ⟨(1-2s_{i,j})(1-2s_{i,j+r})⟩
into `corr_x[r]`, `corr_y[r]` (disconnected). Normalize by sample count
downstream.
"""
function accumulate_spatial!(corr_x::Vector{Float64},
                             corr_y::Vector{Float64},
                             state::AbstractMatrix{Bool})
    L     = size(state, 1)
    N     = L * L
    max_r = length(corr_x)
    invN  = 1.0 / N
    @inbounds for r in 1:max_r
        for i in 1:L, j in 1:L
            ii = mod1(i + r, L)
            jj = mod1(j + r, L)
            s_ij = 1 - 2 * state[i, j]
            corr_x[r] += s_ij * (1 - 2 * state[ii, j]) * invN
            corr_y[r] += s_ij * (1 - 2 * state[i, jj]) * invN
        end
    end
end

"""
    hoshen_kopelman(state, species)

Return a `Vector{Int}` of the sizes of all 4-connected clusters of cells
equal to `species` on the L×L torus `state`. Periodic boundary conditions
are handled by a second wrap-around pass.

Algorithm: raster-scan Hoshen–Kopelman with union-find and path compression,
followed by a second pass that merges labels across row 1 ↔ row L and
column 1 ↔ column L wraps, followed by a flatten-and-count pass. O(N α(N)).

Edge cases:
- Single-cell clusters are counted.
- Clusters that wrap both axes (spanning clusters) end up as one root.
- All-opposite-species state returns `Int[]`.
"""
function hoshen_kopelman(state::AbstractMatrix{Bool}, species::Bool)
    L = size(state, 1)
    labels  = zeros(Int, L, L)
    parents = Int[]   # parents[k] = parent label (or k itself if a root)

    # union-find primitives with path compression
    function _find(k::Int)
        while parents[k] != k
            parents[k] = parents[parents[k]]
            k = parents[k]
        end
        return k
    end
    function _unite!(a::Int, b::Int)
        ra = _find(a); rb = _find(b)
        if ra != rb
            parents[max(ra, rb)] = min(ra, rb)
        end
    end

    # Pass 1: raster scan using only up and left neighbors.
    @inbounds for i in 1:L, j in 1:L
        state[i, j] == species || continue
        up   = (i > 1 && state[i-1, j] == species) ? labels[i-1, j] : 0
        left = (j > 1 && state[i, j-1] == species) ? labels[i, j-1] : 0
        if up == 0 && left == 0
            push!(parents, length(parents) + 1)
            labels[i, j] = length(parents)
        elseif up == 0
            labels[i, j] = left
        elseif left == 0
            labels[i, j] = up
        else
            labels[i, j] = min(up, left)
            up != left && _unite!(up, left)
        end
    end

    # Pass 2: periodic-boundary merges (row 1↔L, col 1↔L).
    @inbounds for k in 1:L
        if state[1, k] == species && state[L, k] == species
            _unite!(labels[1, k], labels[L, k])
        end
        if state[k, 1] == species && state[k, L] == species
            _unite!(labels[k, 1], labels[k, L])
        end
    end

    # Pass 3: flatten each site's label to its root and accumulate size.
    size_by_root = Dict{Int, Int}()
    @inbounds for i in 1:L, j in 1:L
        lab = labels[i, j]
        lab == 0 && continue
        r = _find(lab)
        size_by_root[r] = get(size_by_root, r, 0) + 1
    end
    return collect(values(size_by_root))
end
